In [1]:
##Numpy - Numerical python
##Pandas
##Matplotlib
##Seaborn

In [2]:
#Vectors = 1 dimensional array
#matrices = 2 dimensional array

In [1]:
import numpy as np

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
##arange = returns evely spaced values within a given interval

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.full((3,3),4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [24]:
np.full((4,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [25]:
##linspace - returns evenly spaced numbers over a specified interval

In [27]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [43]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

RANDOM

In [34]:
#rand = it creates an array of the given shape and populates it with random numbers from a uniform distribution [0, 1)`

In [40]:
np.random.rand(100)

array([0.47720379, 0.00856289, 0.56920654, 0.54323312, 0.50688632,
       0.70627903, 0.39761441, 0.86889638, 0.05636812, 0.48651854,
       0.41542356, 0.52198487, 0.01795919, 0.76279639, 0.34745977,
       0.99739053, 0.35212567, 0.25503305, 0.58670704, 0.89345183,
       0.02088898, 0.37974622, 0.08490875, 0.07885819, 0.04468597,
       0.53898658, 0.41960243, 0.87678393, 0.88735164, 0.55611735,
       0.61279784, 0.8319184 , 0.48634307, 0.71635516, 0.20602239,
       0.3475118 , 0.0785878 , 0.4101656 , 0.27644882, 0.276481  ,
       0.3509509 , 0.73454743, 0.05322519, 0.74559155, 0.93238544,
       0.13930956, 0.20317383, 0.98263086, 0.37554794, 0.13234094,
       0.76300028, 0.72261925, 0.09338591, 0.44434427, 0.29302907,
       0.12973242, 0.13514713, 0.06594064, 0.68427505, 0.8766478 ,
       0.31635873, 0.99218934, 0.59983815, 0.89720304, 0.00259515,
       0.6470133 , 0.41008248, 0.1693618 , 0.16206953, 0.82918191,
       0.28403169, 0.36155256, 0.60078564, 0.02111539, 0.72505

In [44]:
np.random.rand(5,5)

array([[0.09268661, 0.94248445, 0.54605308, 0.51130447, 0.57051264],
       [0.56916679, 0.81282183, 0.52553876, 0.12635082, 0.91694049],
       [0.11562571, 0.87196685, 0.30331949, 0.25439874, 0.99832529],
       [0.43811847, 0.21953355, 0.01672928, 0.03338875, 0.49389856],
       [0.42407102, 0.13969862, 0.04344878, 0.74399911, 0.57362884]])

In [45]:
##randn = returns a sample from the "standard normal" distribution.

In [50]:
np.random.randn(2)

array([ 1.29776012, -0.70424666])

In [48]:
np.random.randn(5,5)

array([[-1.45096387, -1.38743309, -1.54502364,  0.94865366,  1.65139802],
       [-1.6397403 ,  2.03618954, -1.51967299, -1.28329081, -0.89617356],
       [ 1.55400844, -0.55392036,  0.16120265,  0.25655598, -0.50549819],
       [ 0.0405326 ,  1.98614217,  0.51614366, -0.28616849, -0.09330075],
       [ 0.94519442,  1.26395481,  0.92096453,  1.49161446,  0.28722325]])

In [ ]:
##randint = generate random integers within a specified interval

In [53]:
np.random.randint(1,10)

7

In [54]:
np.random.randint(1,10,5)

array([7, 2, 3, 9, 2])

In [55]:
arr = np.arange(25)

In [57]:
randarr = np.random.randint(0,50,10)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
randarr

array([35, 35,  6, 48, 45,  6, 44, 26, 32, 16])

In [59]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
arr.reshape(4,4)

ValueError: cannot reshape array of size 25 into shape (4,4)

SHAPE

In [63]:
arr.shape

(25,)

In [64]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [65]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [66]:
arr.dtype

dtype('int64')

INDEXING AND SELECTION

In [67]:
arr2 = np.arange(0,11)

In [68]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr[8]

8

In [71]:
arr2[0]

0

In [72]:
arr2[1:5]

array([1, 2, 3, 4])

In [73]:
arr[4:8]

array([4, 5, 6, 7])

In [74]:
#indexing in a 2dimensional array

#1. double bracket format === [row][column]
#2. single bracket format(using commas to seprate the row and column)[row,column]

In [76]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [77]:
arr_2d[1][0]

20

In [78]:
arr_2d[1,0]

20

In [79]:
arr_2d[2,2]

45

In [80]:
##picking an entire row

In [83]:
arr_2d[0]

array([ 5, 10, 15])

In [84]:
##picking an entire column

In [87]:
arr_2d[:,0]

array([ 5, 20, 35])

In [99]:
arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [100]:
arr_2d[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [104]:
##changing the values of a row
arr_2d[1] = [1,2,3]
arr_2d

array([[ 5, 10, 15],
       [ 1,  2,  3],
       [35, 40, 45]])

In [107]:
##changing the values of a column
arr_2d[:,1] = [4,5,6]
arr_2d

array([[ 5,  4, 15],
       [ 1,  5,  3],
       [35,  6, 45]])

In [110]:
arr_2d[2] = 10
arr_2d

array([[ 5,  4, 15],
       [ 1,  5,  3],
       [10, 10, 10]])

##ARRAY CONCATENATION AND SPLITTING

In [4]:
x = np.array([2,4,6])
y = np.array([8,10,12])

np.concatenate([x,y])

array([ 2,  4,  6,  8, 10, 12])

In [6]:
z = np.array([14,16,18])

np.concatenate([x,y,z])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
##axis = 0 === column
##axis = 1 === row

In [10]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
grid2 = np.array([[7,8,9],[10,11,12]])
grid2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [14]:
np.concatenate([grid,grid2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [18]:
np.concatenate([grid,grid2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
##vstack - vertical stacking
##hstack - horizontal stacking

In [20]:
x

array([2, 4, 6])

In [21]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.vstack([x,grid])

array([[2, 4, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [26]:
np.hstack([grid2,grid])

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

In [27]:
##splitting an array

In [55]:
x = [1,2,3,11,12,13,21,22]
x1,x2= np.split(x,[3])
print(x1,x2)

[1 2 3] [11 12 13 21 22]


In [31]:
x = [1,2,3,11,12,13,21,22]
x1,x2,x3 = np.split(x,[3,6])
print(x1,x2,x3)

[1 2 3] [11 12 13] [21 22]


In [33]:
grid = np.arange(25)
grid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
grid = grid.reshape(5,5)
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
##vsplit = vertical split ==== upper, lower === Split an array into multiple sub-arrays vertically (row-wise).
##hsplit = horizontal split ==== left, right === Split an array into multiple sub-arrays horizontally (column-wise).

In [48]:
upper, lower = np.vsplit(grid, [2])
print(upper)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [49]:
print(lower)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [52]:
left, right = np.hsplit(grid, [2])
print(left)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]


In [53]:
print(right)

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


BOOLEAN MASK

In [57]:
x = np.arange(-3, 5)
x

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [58]:
#create a boolean mask of x for values less than or equal to 2

In [59]:
x <= 2

array([ True,  True,  True,  True,  True,  True, False, False])

In [60]:
##for values equal to -1

In [61]:
x == -1

array([False, False,  True, False, False, False, False, False])

In [62]:
## for all positive values

In [63]:
0 < x

array([False, False, False, False,  True,  True,  True,  True])

In [64]:
## a boolean mask of x for all even values

In [66]:
x % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [70]:
list1 = [1,2,3,4,5,6]

In [71]:
np.equal(list1, 4)

array([False, False, False,  True, False, False])

In [72]:
np.greater(list1, 2)

array([False, False,  True,  True,  True,  True])

In [73]:
np.less(list1, 3)

array([ True,  True, False, False, False, False])

In [80]:
x1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
x1 < 5

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [82]:
np.less(x1, 5)

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

##MASKING

In [83]:
x1[x1 < 5]

array([1, 2, 3, 4])

In [84]:
x1[x1 >6]

array([7, 8, 9])

In [85]:
x[x <= 2]

array([1, 2])

###COMPUTATIONS, AGGREGATIONS AND SUMMARY STATISTICS

In [87]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [89]:
arr + 5  ##addition

array([5, 6, 7, 8, 9])

In [90]:
arr - 5  ##subtraction

array([-5, -4, -3, -2, -1])

In [91]:
arr * 5  ##multiplication

array([ 0,  5, 10, 15, 20])

In [92]:
arr / 5  ##division

array([0. , 0.2, 0.4, 0.6, 0.8])

In [93]:
arr // 5  ##floor division

array([0, 0, 0, 0, 0])

In [94]:
arr ** 2

array([ 0,  1,  4,  9, 16])

In [95]:
arr % 2

array([0, 1, 0, 1, 0])

In [110]:
arr2 = np.array([-2,-6,-4,3,2])
arr2

array([-2, -6, -4,  3,  2])

In [111]:
abs(arr2)

array([2, 6, 4, 3, 2])

In [96]:
(-2 * arr + 1) ** 6

array([     1,      1,    729,  15625, 117649])

In [99]:
list3 = [10,20,30,40,50]
list3
list4 = [60,70,80,90,100]
list4

[60, 70, 80, 90, 100]

In [101]:
np.add(list3, 3)

array([13, 23, 33, 43, 53])

In [102]:
np.subtract(list3, 3)

array([ 7, 17, 27, 37, 47])

In [103]:
np.multiply(list3, 3)

array([ 30,  60,  90, 120, 150])

In [104]:
np.divide(list3, 3)

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [105]:
np.floor_divide(list3, 3)

array([ 3,  6, 10, 13, 16])

In [106]:
np.power(list3, 2)

array([ 100,  400,  900, 1600, 2500])

In [108]:
np.mod(list3, 3)

array([1, 2, 0, 1, 2])

In [113]:
np.negative(list3)

array([-10, -20, -30, -40, -50])

###SUMMARY STATISTICS

In [115]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [116]:
a.sum()

15

In [117]:
a.mean()

3.0

In [120]:
a.std()

1.4142135623730951

In [121]:
a.prod()  ##product(times)

120

In [122]:
a.var()

2.0

In [124]:
a.min()

1

In [126]:
a.max()

5

In [127]:
a.argmin()  ###index of the minimum value

0

In [128]:
a.argmax()

4

In [129]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
b.sum()

45

In [131]:
b.mean()

5.0

In [132]:
b.std()

2.581988897471611

In [133]:
##axis = 0 === column
##axis = 1 === row

In [135]:
b.sum(axis=0)

array([12, 15, 18])

In [136]:
b.mean(axis=1)

array([2., 5., 8.])

In [137]:
b.mean(axis=0)

array([4., 5., 6.])

In [138]:
import pandas as pd

In [144]:
df = pd.read_csv("president_heights.csv")
df.head()

id               name  height_cm
0   1  George Washington        189
1   2         John Adams        170
2   3   Thomas Jefferson        189
3   4      James Madison        163
4   5       James Monroe        183

In [146]:
heights = df["height_cm"].values
heights

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 168, 170, 178, 182, 180,
       183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188,
       188, 182, 185])

In [147]:
heights.mean()

179.73809523809524

In [148]:
heights.min()

163

In [149]:
heights.max()

193

In [150]:
heights.std()

6.931843442745892